// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcabzumeguphttbvbkdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjYWJ6dW1lZ3VwaHR0YnZia2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODU0MTcsImV4cCI6MjA2MTI2MTQxN30.GSSYZo-WNKsTRirgtvx5-sThLfTsWZAKAcW8FB4RIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);